playbook file
sjamgade/monasca-autoscaling pull request #2
Opened 2019-04-24 15:46 UTC by sjamgade

2019-04-25 19:55 UTC, witekest requested changes

2019-04-25 19:55 UTC, witekest commented on playbook.md
> +  ssh cirros@$FLOATING_IP "dd if=/dev/zero of=/dev/null &"
Logging into the instance does not work in the OVH environment.

2019-04-27 01:12 UTC, jodavis-suse reviewed
Looking for things to clarify as I went through it.

2019-04-27 01:12 UTC, jodavis-suse commented on playbook.md
> +`openstack stack create --wait -t autoscaling.yaml test`
At line 14 we instruct them to call the stack 'test', but on line 21 we reference 'teststack'

2019-04-27 01:12 UTC, jodavis-suse commented on autoscaling.yaml
> +          metadata : {"scale_group": {get_param: "OS::stack_id"}}
extra space added here.

2019-04-27 01:12 UTC, jodavis-suse commented on playbook.md
> +`monasca metric-list`
I get an empty list on my devstack at this 'monasca metric-list' command unless I change the rc file to use mini-mon as the user (or sign in another session which picks up the mini-mon env).

2019-04-27 01:12 UTC, jodavis-suse commented on playbook.md
> +`monasca measurement-list`
Might give a hint about how to format the time.
date -Iseconds | sed -e "s/.\{6\}$/Z/"
or -120

2019-04-27 01:12 UTC, jodavis-suse commented on playbook.md
> +- Fill out  *scale_up_policy* and *scale_up_policy*:
Second should be "scale_down_policy"

2019-04-27 20:03 UTC, merged

2019-04-27 20:03 UTC, sjamgade commented
Merging for now, @jodavis-suse I will address your comments in master